### ISSUE TITLE
Issue identified with Vagrant image

### ISSUE THREAD

**Issue by wingZero21** [thanandorn/puppet-pulp#1]
Hey,

I was trying the vagrant image and noticed a couple of issues I thought I would mention.

1) The repo's that are getting added are missing the name bit within the repo.

```
name=pulp-init
```

2) On the vagrant image that is getting used, once the repo works by adding the name to the pulp-init,pulp-epel repos its complaining with the below error. 

`[Errno 14] problem making ssl connection`

To fix this we just need to update the ca-certificates that is being installed with the base OS.

Regards
Mark

**Comment by thanandorn** [comment]
Hi Mark,

My module has not been touched since pulp v.1
Please feel free to use and modify as you like.

For the second one, it might be easily to just update the image to CentOS 6.5

http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box

Cheers,
Tron

**Comment by wingZero21** [comment]
Ok Cool cheers, did not realise it was v1 so might just take a look at doing something else maybe.

Also just noticed when adding that locally it does not seem to be adding the name to the repo like it should, not really sure why that would be!

**Comment by thanandorn** [comment]
I believe `descr` directive is the one.
